### ISSUE TITLE
Icon for the Recycle bin

### ISSUE THREAD

**Issue by ruohki** [m4thewz/dracula-icons#1]
Hey, is it possible to have a recycle bin icon added to the collection?

**Comment by matheuuus** [comment]
In progress, coming soon its completed

**Comment by m4thewz** [comment]
Sorry for delay, but it was added in [5f55c7e](https://github.com/m4thewz/dracula-icons/commit/5f55c7e5157cfd2874e0698c71e3ac290ae1252f)
