### ISSUE TITLE
Icons for JetBrains IDE's

### ISSUE THREAD

**Issue by denis-rossati** [m4thewz/dracula-icons#3]
Is it possible to create icons at least for the main JetBrains tools? 

They look kinda ugly between the dracula icons:

![Screenshot from 2022-04-16 14-52-27](https://user-images.githubusercontent.com/74881282/163686217-74d9435b-d8c2-4ef2-a609-5edd1ff6a4b1.png)

**Comment by m4thewz** [comment]
Icons updated in [5f55c7e](https://github.com/m4thewz/dracula-icons/commit/5f55c7e5157cfd2874e0698c71e3ac290ae1252f)
