### ISSUE TITLE
Update Thunderbird icon

### ISSUE THREAD

**Issue by SunRed** [m4thewz/dracula-icons#7]
With the release of Thunderbird 115 the icon was updated
(SVG image)
![Thunderbird Logo](https://hg.mozilla.org/comm-central/raw-file/tip/mail/branding/thunderbird/content/logo-gradient.svg)

https://hg.mozilla.org/comm-central/file/tip/mail/branding/thunderbird
https://design.thunderbird.net/resources/logo

**Comment by m4thewz** [comment]
Icon updated in [5f55c7e](https://github.com/m4thewz/dracula-icons/commit/5f55c7e5157cfd2874e0698c71e3ac290ae1252f)
